#rgb("ffffff")
#plugin("../a.wasm")
#bibliography(("../a.bib", "../b.bib"), style: "../c.csl", title: [Errorz])
#cite(style: "../a.csl", supplement: [Errorz])
#raw(syntaxes: ("../a", "../b"), theme: "../c", [Errorz])
#image("../a", caption: [Errorz])
#regex("(?i)")
#std.rgb("ffffff")
#color.rgb("ffffff")
#std.plugin("../a.wasm")
#std.bibliography(("../a.bib", "../b.bib"), style: "../c.csl", title: [Errorz])
#std.cite(style: "../a.csl", supplement: [Errorz])
#std.raw(syntaxes: ("../a", "../b"), theme: "../c", [Errorz])
#std.image("../a", caption: [Errorz])
#std.regex("(?i)")
#datetime.today().display("y:[year repr:last_two]")
#context counter(heading).display("i", both: [Errorz])
